name: custom_alert
description: A new Flutter project.
version: 0.0.1
homepage: https://github.com/MrPresidentWhite/custom_alert.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  assets:
    - assets/images/2.0x/close.png
    - assets/images/2.0x/icon_error.png
    - assets/images/2.0x/icon_info.png
    - assets/images/2.0x/icon_success.png
    - assets/images/2.0x/icon_warning.png
    - assets/images/3.0x/close.png
    - assets/images/3.0x/icon_error.png
    - assets/images/3.0x/icon_info.png
    - assets/images/3.0x/icon_success.png
    - assets/images/3.0x/icon_warning.png
    - assets/images/close.png
    - assets/images/icon_error.png
    - assets/images/icon_info.png
    - assets/images/icon_success.png
    - assets/images/icon_warning.png